---
title: "regressionResultsStargazer"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## R Markdown

<!-- % Table created by stargazer v.5.2 by Marek Hlavac, Harvard University. E-mail: hlavac at fas.harvard.edu -->
<!-- % Date and time: Mon, Apr 16, 2018 - 22:27:38 -->
<!-- \begin{table}[!htbp] \centering  -->
<!--   \caption{Regression Table}  -->
<!--   \label{}  -->
<!-- \begin{tabular}{@{\extracolsep{5pt}}lccc}  -->
<!-- \\[-1.8ex]\hline  -->
<!-- \hline \\[-1.8ex]  -->
<!--  & \multicolumn{3}{c}{\textit{Dependent variable:}} \\  -->
<!-- \cline{2-4}  -->
<!-- \\[-1.8ex] & \multicolumn{3}{c}{Malaria (fever)} \\  -->
<!--  & Basic & Partial & Full \\  -->
<!-- \\[-1.8ex] & (1) & (2) & (3)\\  -->
<!-- \hline \\[-1.8ex]  -->
<!--  deforestation0YearLag & $-$0.015$^{**}$ & $-$0.011 & $-$0.006 \\  -->
<!--   & (0.007) & (0.007) & (0.008) \\  -->
<!--   & & & \\  -->
<!--  deforestation1YearLag & $-$0.002 & $-$0.008 & 0.014 \\  -->
<!--   & (0.011) & (0.011) & (0.011) \\  -->
<!--   & & & \\  -->
<!--  deforestation2YearLag & $-$0.007 & $-$0.013$^{*}$ & $-$0.010 \\  -->
<!--   & (0.007) & (0.007) & (0.007) \\  -->
<!--   & & & \\  -->
<!--  deforestation3YearLag & $-$0.002 & 0.010$^{*}$ & 0.010 \\  -->
<!--   & (0.006) & (0.006) & (0.006) \\  -->
<!--   & & & \\  -->
<!--  Constant & 0.191$^{***}$ & 0.151$^{***}$ & 0.154$^{***}$ \\  -->
<!--   & (0.006) & (0.009) & (0.040) \\  -->
<!--   & & & \\  -->
<!-- \hline \\[-1.8ex]  -->
<!-- Year Fixed Effects & No & Yes & Yes \\  -->
<!-- Seasonality & No & Yes & Yes \\  -->
<!-- HH and indiv controls & No & No & Yes \\  -->
<!-- \hline \\[-1.8ex]  -->
<!-- Observations & 14,027 & 14,027 & 14,027 \\  -->
<!-- R$^{2}$ & 0.001 & 0.007 & 0.036 \\  -->
<!-- Adjusted R$^{2}$ & 0.0004 & 0.006 & 0.032 \\  -->
<!-- Residual Std. Error & 0.396 (df = 14021) & 0.395 (df = 14010) & 0.389 (df = 13956) \\  -->
<!-- F Statistic & 2.217$^{**}$ (df = 5; 14021) & 6.081$^{***}$ (df = 16; 14010) & 7.540$^{***}$ (df = 70; 13956) \\  -->
<!-- \hline  -->
<!-- \hline \\[-1.8ex]  -->
<!-- \textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\  -->
<!-- \end{tabular}  -->
<!-- \end{table} -->


% Table created by stargazer v.5.2 by Marek Hlavac, Harvard University. E-mail: hlavac at fas.harvard.edu
% Date and time: Tue, Apr 17, 2018 - 18:24:12

This is the regression output from once I fixed the error with tree cover no data.

\begin{table}[!htbp] \centering 
  \caption{Regression Table} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}}lccc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\ 
\cline{2-4} 
\\[-1.8ex] & \multicolumn{3}{c}{Malaria (fever)} \\ 


\\[-1.8ex] & (1) & (2) & (3)\\ 
\hline \\[-1.8ex] 
 deforestation0YearLag & $-$1.522$^{**}$ & $-$0.707 & $-$0.844 \\ 
  & (0.743) & (0.885) & (0.885) \\ 
  & & & \\ 
 deforestation1YearLag & $-$0.074 & 0.431 & 0.437 \\ 
  & (1.064) & (1.261) & (1.261) \\ 
  & & & \\ 
 deforestation2YearLag & $-$0.419 & $-$0.016 & 0.069 \\ 
  & (0.666) & (0.869) & (0.868) \\ 
  & & & \\ 
 deforestation3YearLag & $-$0.337 & 0.944 & 1.128 \\ 
  & (0.583) & (0.733) & (0.735) \\ 
  & & & \\ 
 Constant & 0.195$^{***}$ & 0.061 & 0.134 \\ 
  & (0.006) & (0.076) & (0.082) \\ 
  & & & \\ 
\hline \\[-1.8ex] 
Regional Fixed Effects & No & Yes & Yes \\
Year Fixed Effects & No & Yes & Yes \\ 
Seasonality & No & Yes & Yes \\ 
HH and indiv controls & No & No & Yes \\ 
\hline \\[-1.8ex] 
Observations & 15,105 & 15,105 & 15,105 \\ 
R$^{2}$ & 0.001 & 0.048 & 0.056 \\ 
Adjusted R$^{2}$ & 0.0004 & 0.036 & 0.043 \\ 
Residual Std. Error & 0.397 (df = 15099) & 0.390 (df = 14916) & 0.389 (df = 14891) \\ 
F Statistic & 2.119$^{*}$ (df = 5; 15099) & 3.960$^{***}$ (df = 188; 14916) & 4.151$^{***}$ (df = 213; 14891) \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table}










% Table created by stargazer v.5.2 by Marek Hlavac, Harvard University. E-mail: hlavac at fas.harvard.edu
% Date and time: Tue, Apr 17, 2018 - 18:24:12

These (Table 2) are the regression results I had at the symposium, which was before I noticed the error with tree cover.

\begin{table}[!htbp] \centering 
  \caption{Regression Table} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}}lccc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\ 
\cline{2-4} 
\\[-1.8ex] & \multicolumn{3}{c}{Malaria (fever)} \\ 


\\[-1.8ex] & (1) & (2) & (3)\\ 
\hline \\[-1.8ex] 
 deforestation0YearLag & $-$1.433$^{*}$ & $-$0.500 & $-$0.638 \\ 
  & (0.744) & (0.885) & (0.885) \\ 
  & & & \\ 
 deforestation1YearLag & $-$0.007 & 0.318 & 0.274 \\ 
  & (1.059) & (1.256) & (1.257) \\ 
  & & & \\ 
 deforestation2YearLag & $-$0.617 & 0.248 & 0.308 \\ 
  & (0.658) & (0.868) & (0.867) \\ 
  & & & \\ 
 deforestation3YearLag & $-$0.316 & 0.883 & 1.047 \\ 
  & (0.583) & (0.735) & (0.737) \\ 
  & & & \\ 
 Constant & 0.196$^{***}$ & 0.048 & 0.128 \\ 
  & (0.005) & (0.075) & (0.081) \\ 
  & & & \\ 
\hline \\[-1.8ex] 
Regional Fixed Effects & No & Yes & Yes \\
Year Fixed Effects & No & Yes & Yes \\ 
Seasonality & No & Yes & Yes \\ 
HH and indiv controls & No & No & Yes \\ 
\hline \\[-1.8ex] 
Observations & 15,486 & 15,486 & 15,486 \\ 
R$^{2}$ & 0.001 & 0.046 & 0.054 \\ 
Adjusted R$^{2}$ & 0.0004 & 0.034 & 0.041 \\ 
Residual Std. Error & 0.397 (df = 15480) & 0.391 (df = 15295) & 0.389 (df = 15270) \\ 
F Statistic & 2.116$^{*}$ (df = 5; 15480) & 3.902$^{***}$ (df = 190; 15295) & 4.077$^{***}$ (df = 215; 15270) \\
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table}


